title: Hao ZHANG's Homepage
page-top-title: Hao ZHANG
top-section-bg-text: Information Resource Management
home-subtitle: Hao ZHANG &ensp;|&ensp;<strong>张昊</strong>
copyright-text: '&copy; Hao ZHANG 2024-2030. All Rights Reserved.'
